#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App5.Resource", IsApplication=true)]

namespace App5
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int b1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int b2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int b3 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int b4 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int b5 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int b6 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int b7 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int b8 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int b9 = 2131099659;
			
			// aapt resource value: 0x7f06001d
			public const int bConnect = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int benter = 2131099674;
			
			// aapt resource value: 0x7f06000e
			public const int bexit = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout4 = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout5 = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int linearLayout6 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int listView1 = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int textClock = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int textInfo1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int textInfo2 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int textInfo3 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int textInfo4 = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int textView1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int textView2 = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int textView3 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int textView4 = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int text_ip = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int text_port = 2131099676;
			
			// aapt resource value: 0x7f060012
			public const int txtMessage = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Buttons = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int WatchQueue = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Welcome = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int Connect = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int clock = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int enterQueue = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int txtLayout1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int txtLayout2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int txtLayout3 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int txtLayout4 = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int забрать_справку = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int основнаяОчередь = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int Mono_Android_Theme_Splash = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int button_main = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
